### PR TITLE
Disable the git commid id plugin

### PR DESCRIPTION
**Pull request by endoplasmicR**

### CODE REVIEW

**Comment by JamesRTaylor** [comment]
Can we override this without a commit to lyft/presto? Is it only for master branch? We actually don't use the master branch because we're not able to do a force push on it.

**Comment by endoplasmicR** [comment]
> Can we override this without a commit to lyft/presto? Is it only for master branch? We actually don't use the master branch because we're not able to do a force push on it.

This is the recommendation i got out of the Presto folks:
https://prestosql.slack.com/archives/CP1MUNEUX/p1595378777252000

We might be able to submit this change as a patch

**Comment by JamesRTaylor** [comment]
Let's please fix upstream. We're finally at the point where we have no commits on top of prestosql and it'd be great to keep this unless we have a compelling reason.

**Pull request closed without merging**
